version: 2.1

defaults: &defaults
  resource_class: small
  docker:
    - image: circleci/node:14-buster
  working_directory: ~/sweater-comb

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sweater-comb
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Release
          command: npx semantic-release

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          name: Test

      - release:
          name: Release
          context: nodejs-lib-release
          requires:
            - Test
          filters:
            branches:
              only:
                - main
