version: 2.1

defaults: &defaults
  resource_class: small
  docker:
    - image: circleci/node:14-buster
  working_directory: ~/sweater-comb

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sweater-comb
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: E2E Test
          command: ./end-end-tests/api-standards/test-bulk.bash

  docker-main-release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.7'
      - run:
          name: Build Docker image
          command: IMAGE=ghcr.io/snyk/sweater-comb TAG=optic-main ./scripts/build-docker.bash
      - run:
          name: Push Docker image
          command: |-
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u snyk --password-stdin
            docker push ghcr.io/snyk/sweater-comb:optic-main

  npm-main-release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Release
          command: npx semantic-release

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          name: Test
      - docker-main-release:
          name: Docker Image Release - Main
          requires:
            - Test
          filters:
            branches:
              only:
                - optic-main
