apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      labels:
        app: fake-service
    spec:
      containers:
        - name: fake-service
          image: fake-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

        # TODO: inject woollypully sidecar with admission webhook
        - name: woollypully
          image: woollypully
          imagePullPolicy: Always
          ports:
            - containerPort: 30576
          env:
            - name: PROPOSED_SERVICE_URL
              value: "http://localhost:8080"
            - name: PORT
              value: "30576"

      # TODO: inject woollypully readiness probe with admission webhook
      # Pod is not considered Ready until the probe gets a 200 OK.
      # woollypully doesn't respond 200 OK until governance check on the service container passes.
          readinessProbe:
            httpGet:
              port: 30576
